### ISSUE TITLE
RuntimeError: can't start new thread

### ISSUE THREAD

**Issue by leothronton** [Jerry1014/FundCrawler#20]
爬取进度:[#                        ] 7%Process GetPageByWebWithAnotherProcessAndMultiThreading-1:
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/pi/Documents/myPython/FundCrawler-Dev/CrawlingCore.py", line 115, in run
    t.start()
  File "/usr/lib/python3.7/threading.py", line 847, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
can't start new threadcan't start new thread
^CTraceback (most recent call last):
  File "CrawlingFund.py", line 139, in <module>
    crawling_fund(fund_list)
  File "CrawlingFund.py", line 74, in crawling_fund
    a_result = result_queue.get()
  File "/usr/lib/python3.7/multiprocessing/queues.py", line 94, in get
    res = self._recv_bytes()
  File "/usr/lib/python3.7/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/usr/lib/python3.7/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.7/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
KeyboardInterrupt

能不能加个参数控制一下线程的数量？

**Comment by Jerry1014** [comment]
CrawlingCore.GetPageByWebWithAnotherProcessAndMultiThreading
这个类里面，改个一两行就行

最近一段时间都没空维护的说
