### ISSUE TITLE
第一次运行时报 NotImplementedError

### ISSUE THREAD

**Issue by feeloho** [Jerry1014/FundCrawler#4]
`
正在初始化随机UA模块，若此步消耗了大量时间，请将FakeUA.py中的IF_UPDATE_FAKE_UA修改为False(默认值)
随机UA模块初始化完成
获取基金列表中。。。
共发现8040个基金
Traceback (most recent call last):
  File "/Users/zhaolin/Project/oneself/FundCrawler/CrawlingFund.py", line 181, in <module>
    crawling_fund(GetFundListByWeb())
  File "/Users/zhaolin/Project/oneself/FundCrawler/CrawlingFund.py", line 123, in crawling_fund
    while having_fund_need_to_crawl and result_queue.qsize() < 100 and input_queue.qsize() < 10:
  File "/Users/zhaolin/.pyenv/versions/3.7.0/lib/python3.7/multiprocessing/queues.py", line 117, in qsize
    return self._maxsize - self._sem._semlock._get_value()
NotImplementedError
`

**Comment by JevanWu** [comment]
遇到同样的问题

**Comment by Jerry1014** [comment]
实在对不起，这么久才看到。

似乎这是一个存在于Mac平台的bug
https://github.com/vterron/lemon/issues/11
https://github.com/keras-team/autokeras/issues/368

我试图按照他们的方法修复了一下，却引入一个匪夷所思的新bug。
暂且搁置，等大佬解救，或软件版本更新。

**Comment by Jerry1014** [comment]
很快就有mbp了，等到手了，下一次重构的时候就修复吧。当前暂且忽略。
