### ISSUE TITLE
NotImplementedError

### ISSUE THREAD

**Issue by hdpter** [Jerry1014/FundCrawler#7]
/usr/local/Cellar/python/3.7.6_1/bin/python3 /Users/gongtao/Documents/dev/project/PycharmProjects/FundCrawler/CrawlingFund.py
正在初始化随机UA模块，若此步消耗了大量时间，请将FakeUA.py中的IF_UPDATE_FAKE_UA修改为False(默认值)
随机UA模块初始化完成
获取基金列表中。。。
共发现8408个基金
Traceback (most recent call last):
  File "/Users/gongtao/Documents/dev/project/PycharmProjects/FundCrawler/CrawlingFund.py", line 181, in <module>
    crawling_fund(GetFundListByWeb())
  File "/Users/gongtao/Documents/dev/project/PycharmProjects/FundCrawler/CrawlingFund.py", line 123, in crawling_fund
    while having_fund_need_to_crawl and result_queue.qsize() < 100 and input_queue.qsize() < 10:
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/queues.py", line 117, in qsize
    return self._maxsize - self._sem._semlock._get_value()
NotImplementedError

**Comment by Jerry1014** [comment]
看另外一个Issue，mac os的兼容问题由于手头上没有mac设备，暂时修不了
