### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by seanhsuu** [Jerry1014/FundCrawler#8]
报错信息：
Traceback (most recent call last):
  File "CrawlingFund.py", line 181, in <module>
    crawling_fund(GetFundListByWeb())
  File "CrawlingFund.py", line 142, in crawling_fund
    new_fund_info: FundInfo = fund_web_page_parse.send(a_result[1:])
  File "ParsingHtml.py", line 72, in _parse_fund_info
    re.search(r'基金规模</a>：((?:\d+(?:\.\d{2}|)|--)亿元.*?)<', page_context).group(1))
AttributeError: 'NoneType' object has no attribute 'group'

麻烦看一下呢~~

**Comment by Jerry1014** [comment]
已知问题，是由于多线程信息同步逻辑不正确导致的。
计划在下一次重构中修复。
感谢。
