### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by kali404** [Jerry1014/FundCrawler#9]
Traceback (most recent call last):
  File "D:/Desktops/FundCrawler/CrawlingFund.py", line 181, in <module>
    crawling_fund(GetFundListByWeb())
  File "D:/Desktops/FundCrawler/CrawlingFund.py", line 142, in crawling_fund
    new_fund_info: FundInfo = fund_web_page_parse.send(a_result[1:])
  File "D:\Desktops\FundCrawler\ParsingHtml.py", line 72, in _parse_fund_info
    re.search(r'基金规模</a>：((?:\d+(?:\.\d{2}|)|--)亿元.*?)<', page_context).group(1))
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by kali404** [comment]
我尝试捕捉这个错误代码中的page_dcontext.但是却没有任何发现

**Comment by kali404** [comment]
那个我没有切换到Dev分支,好吧我错了
